[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
FrameworkDemo = "cfbf7e84-66d2-421e-b147-9edb7a8672d2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
BenchmarkTools = "1.5"
FrameworkDemo = "0.1"
Plots = "1.40"
Printf = "1.11"
julia = "1.11"

[sources]
FrameworkDemo = {path = ".."}
