name = "FrameworkDemo"
uuid = "cfbf7e84-66d2-421e-b147-9edb7a8672d2"
authors = ["SmalRat <30555080+SmalRat@users.noreply.github.com>", "Mateusz Jakub Fila <mateusz.jakub.fila@cern.ch>", "hegner <benedikt.hegner@cern.ch>", "Josh Ott <joshott16@gmail.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedNext = "fab6aee4-877b-4bac-a744-3eca44acbb6f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GraphMLReader = "8e6830a9-644c-4485-8539-40ee18e3ca8c"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[sources]
GraphMLReader = {rev = "master", url = "https://github.com/SmalRat/GraphMLReader.jl"}

[compat]
Aqua = "0.8"
ArgParse = "1.2"
CSV = "0.10"
Dagger = "0.18.14"
DataFrames = "1.6"
Distributed = "1.11"
DistributedNext = "1.0"
FileIO = "1.16"
GraphMLReader = "0.1"
GraphViz = "0.2"
Graphs = "1"
JSON3 = "1.14"
Logging = "1.11"
MetaGraphs = "0.7, 0.8"
Plots = "1.40"
Preferences = "1.4"
Printf = "1.11"
Test = "1.11"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Logging", "Test"]

[preferences.Dagger]
distributed-package = "DistributedNext"
[preferences.MemPool]
distributed-package = "DistributedNext"
[preferences.TimespanLogging]
distributed-package = "DistributedNext"
