name = "FrameworkDemo"
uuid = "cfbf7e84-66d2-421e-b147-9edb7a8672d2"
authors = ["SmalRat <30555080+SmalRat@users.noreply.github.com>",
           "Mateusz Jakub Fila <mateusz.jakub.fila@cern.ch>",
           "hegner <benedikt.hegner@cern.ch>"]
version = "0.1.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
DaggerWebDash = "cfc5aa84-1a2a-41ab-b391-ede92ecae40c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TimespanLogging = "a526e669-04d3-4846-9525-c66122c55f63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
Dagger = "0.18.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]